# -*- coding: utf-8 -*-

from . import ir_ui_view
from . import res_company
from . import product_category
from . import product_template
from . import product_product
from . import uom_uom
from . import poultry_coop
from . import poultry_batch
from . import poultry_batch_coop_line
from . import poultry_batch_movement
from . import poultry_batch_period_change
from . import poultry_coop_bom
from . import poultry_indicator
from . import poultry_genetics_standard_version
from . import poultry_genetics
from . import poultry_genetics_standard
from . import poultry_batch_indicator_value
from . import poultry_batch_indicator_weekly_value
from . import poultry_mortality
from . import poultry_cage
from . import poultry_weight_record
from . import poultry_weight_record_line
from . import poultry_vaccine
from . import poultry_vaccination_plan
from . import poultry_vaccination_plan_line
from . import poultry_batch_vaccination_plan
from . import poultry_vaccination
from . import poultry_vaccination_compliance
from . import poultry_egg_collection
from . import poultry_egg_collection_line
from . import poultry_egg_collection_line_uom
from . import mrp_bom
from . import mrp_bom_line
from . import mrp_production
from . import mrp_unbuild
from . import poultry_stock_move
from . import poultry_coop_close
from . import poultry_coop_close_wizard
from . import poultry_config_settings
from . import poultry_recompute_indicators_wizard
from . import poultry_zero_mortality_wizard

